# Arquivo de configuração da Netlify
# Este arquivo garante que as variáveis de ambiente estarão disponíveis
# tanto durante o build quanto na execução das funções da API.

[build]
  # Comando que a Netlify irá rodar
  command = "npm run build"
  # Pasta onde o resultado do build do Next.js fica
  publish = ".next"

# Bloco de configuração do plugin Next.js da Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Bloco MAIS IMPORTANTE: Variáveis de Ambiente
[build.environment]
  # Cole aqui a sua URL de conexão do Neon com POOLING e o parâmetro pgbouncer
  DATABASE_URL = "postgresql://neondb_owner:npg_hYJik2Hx9rdC@ep-silent-moon-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&pgbouncer=true"
  
  # Cole aqui a sua chave secreta do NextAuth
  NEXTAUTH_SECRET = ";oQo~:$xWiiuU#P6"